# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-11-30 22:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import folder.validators


class Migration(migrations.Migration):

    dependencies = [
        ('folder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('user_item', models.FileField(upload_to=b'', validators=[folder.validators.validate_file_extension])),
                ('approved_item', models.BooleanField(default=False)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='folder.Folder')),
            ],
        ),
    ]
